### ISSUE TITLE
kubernets部署dtm出现错误

### ISSUE THREAD

**Issue by xbclub** [dtm-labs/dtm#196]
平台：k8s 1.21.5
部署yaml：
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dtm
  labels:
    app: dtm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dtm
  template:
    metadata:
      labels:
        app: dtm
    spec:
      containers:
        - name: dtm
          image: yedf/dtm:1.11.0
          imagePullPolicy: IfNotPresent
          args:
            - "-c=/app/dtm/configs/config.yaml"
          volumeMounts:
            - mountPath: /app/dtm/configs
              name: config
          ports:
            - containerPort: 36789
              protocol: TCP
              name: http
            - containerPort: 36790
              protocol: TCP
              name: grpc
          livenessProbe:
            httpGet:
              path: /api/ping
              port: 36789
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: /api/ping
              port: 36789
              scheme: HTTP
          resources:
            requests:
              cpu: 200m
              memory: 200Mi
      volumes:
        - name: config
          configMap:
            name: dtm-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: dtm-conf
  labels:
    app: dtm
data:
  config.yaml: |-
    Store:
      Driver: mysql
      Host: mysqlhost
      Port: 3306
      User: mysqluser
      Password: 'mysqlpass'
---
apiVersion: v1
kind: Service
metadata:
  name: dtm-svc
  labels:
    app: dtm
spec:
  ports:
    - port: 8080
      targetPort: 36790
      name: grpc
      appProtocol: grpc # Kubernetes v1.20 [stable]，低版本请剔除此行
    - port: 80
      targetPort: 36789
      name: http
      appProtocol: http # Kubernetes v1.20 [stable]，低版本请剔除此行
  selector:
    app: dtm
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dtm
  annotations:
    alb.ingress.kubernetes.io/scheme: internal
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/success-codes: "200"
    alb.ingress.kubernetes.io/load-balancer-name: dtm
    alb.ingress.kubernetes.io/healthcheck-path: /api/ping
spec:
  ingressClassName: alb
  rules:
    - host: example.com
      http:
        paths:
          - backend:
              service:
                name: dtm-svc
                port:
                  number: 80
            path: /
            pathType: Prefix

```
错误日志：
```json
{"level":"error","ts":"2022-01-25T07:31:10.124Z","caller":"dtmsvr/cron.go:63","msg":"----recovered panic http/grpc result should be specified as in:\nhttps://dtm.pub/summary/arch.html#http\nunkown result will be retried: Post \"http://host.docker.internal:8081/api/barrierTransInConfirm?branch_id=02&gid=uL8g2XXz9U7x3ke3gnZNHJ&op=confirm&trans_type=tcc\": dial tcp: lookup host.docker.internal on 172.20.0.10:53: no such host\ngoroutine 34 [running]:\nruntime/debug.Stack(0xc000105da0, 0x1d04200, 0xc0007a2870)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9f\ngithub.com/dtm-labs/dtm/dtmsvr.handlePanic(0x0)\n\t/app/dtm/dtmsvr/cron.go:63 +0x5b\npanic(0x1d04200, 0xc0007a2870)\n\t/usr/local/go/src/runtime/panic.go:965 +0x1b9\ngithub.com/dtm-labs/dtm/dtmcli/dtmimp.PanicIf(...)\n\t/app/dtm/dtmcli/dtmimp/utils.go:75\ngithub.com/dtm-labs/dtm/dtmsvr.CronTransOnce(0xc0009876b0, 0x16)\n\t/app/dtm/dtmsvr/cron.go:38 +0x1e7\ngithub.com/dtm-labs/dtm/dtmsvr.CronExpiredTrans(0xffffffffffffffff)\n\t/app/dtm/dtmsvr/cron.go:45 +0x3e\ncreated by main.main\n\t/app/dtm/main.go:72 +0x210\n","stacktrace":"github.com/dtm-labs/dtm/dtmsvr.handlePanic\n\t/app/dtm/dtmsvr/cron.go:63\nruntime.gopanic\n\t/usr/local/go/src/runtime/panic.go:965\ngithub.com/dtm-labs/dtm/dtmcli/dtmimp.PanicIf\n\t/app/dtm/dtmcli/dtmimp/utils.go:75\ngithub.com/dtm-labs/dtm/dtmsvr.CronTransOnce\n\t/app/dtm/dtmsvr/cron.go:38\ngithub.com/dtm-labs/dtm/dtmsvr.CronExpiredTrans\n\t/app/dtm/dtmsvr/cron.go:45"}
```
