### ISSUE TITLE
Problem when setting config.Store values inside helm chart

### ISSUE THREAD

**Issue by ostafen** [dtm-labs/dtm#377]
I was trying to deploy dtm in my kubernetes cluster using the helm chart provided in the repo. However, when I set the following configuration key for pointing to a postgres instance:

```yml
# Default values for dtm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# DTM configuration. Specify content for config.yaml
# ref: https://github.com/dtm-labs/dtm/blob/main/conf.sample.yml
configuration: |-
 Store: # specify which engine to store trans status
  Driver: 'postgres' # default store engine
  Host: 'someurl'
  User: 'someuser'
  Password: 'somepassword'
  Port: 5432
  Db: 'dtm'
  Schema: 'public'
```

I get the following error:

```bash
2022/11/28 15:43:14 fatal error: yaml: unmarshal errors:
line 7: field Db not found in type config.Store
line 8: field Schema not found in type config.Store
```

Values seem exactly the ones provided in the sample config.yml file.
Any idea on how to fix this?
