### ISSUE TITLE
docker compose  怎么配置文件读取配置文件

### ISSUE THREAD

**Issue by erdong01** [dtm-labs/dtm#498]
version: '3'
services:
  dtm:
    image: yedf/dtm
    environment:
      STORE_DRIVER: redis
      STORE_HOST: 116.62.176.165
      STORE_USER: ''
      STORE_PASSWORD: 'maile~maile'
      STORE_PORT: 6379
      # MicroService: 'dtm'
    working_dir: /var/dtm/config
    entrypoint:
      - -c /var/dtm/config/conf.yaml
    volumes:
      - ./config/:/var/dtm/config/
    ports:
      - '36789:36789'
      - '36790:36790'
这样写直接报：ERROR: for dtm  Cannot start service dtm: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "-c /var/dtm/config/conf.yaml": stat -c /var/dtm/config/conf.yaml: no such file or directory: unknown
错误没搞懂

**Comment by yedf2** [comment]
你这个问题感觉是docker相关的问题，你可以问问熟悉docker的人帮你看看

**Comment by vim-z** [comment]
> 你们有能正常用引入，并成功加载配置文件的例子吗

```yml
services:
  dtm:
    image: yedf/dtm
    container_name: dtm
    volumes:
      - ./dtm/conf/config.yml:/etc/dtm/config.yml
    ports:
      - "36789:36789"
      - "36790:36790"
    entrypoint:
      /app/dtm/dtm -c /etc/dtm/config.yml
```
这样可以成功
